# 本文件只做“统一导出”：外部模块可以从 core.bus 导入常用协议类型。
# 真正的模型定义仍在 envelope.py、commands.py 和 events.py 中。
# S1 在这里新增 Run / Step / Tool / LLM 事件的便捷导出；不要在本文件寻找业务逻辑。
from kama_claude.core.bus.commands import Command, PingCommand, PongResult
from kama_claude.core.bus.envelope import (
    INTERNAL_ERROR,
    INVALID_PARAMS,
    INVALID_REQUEST,
    METHOD_NOT_FOUND,
    PARSE_ERROR,
    JsonRpcError,
    JsonRpcErrorObject,
    JsonRpcRequest,
    JsonRpcSuccess,
    make_error,
)
from kama_claude.core.bus.events import (
    CoreStartedEvent,
    Event,
    LlmModelSelectedEvent,
    LlmTokenEvent,
    LlmUsageEvent,
    LogLineEvent,
    RunFinishedEvent,
    RunStartedEvent,
    StepFinishedEvent,
    StepStartedEvent,
    ToolCallFailedEvent,
    ToolCallFinishedEvent,
    ToolCallStartedEvent,
)

__all__ = [
    "Command",
    "CoreStartedEvent",
    "Event",
    "LogLineEvent",
    "LlmModelSelectedEvent",
    "LlmTokenEvent",
    "LlmUsageEvent",
    "RunFinishedEvent",
    "RunStartedEvent",
    "StepFinishedEvent",
    "StepStartedEvent",
    "ToolCallFailedEvent",
    "ToolCallFinishedEvent",
    "ToolCallStartedEvent",
    "INTERNAL_ERROR",
    "INVALID_PARAMS",
    "INVALID_REQUEST",
    "JsonRpcError",
    "JsonRpcErrorObject",
    "JsonRpcRequest",
    "JsonRpcSuccess",
    "METHOD_NOT_FOUND",
    "PARSE_ERROR",
    "PingCommand",
    "PongResult",
    "make_error",
]
